//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 llmos.ai.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1

import (
	common "github.com/llmos-ai/llmos-operator/pkg/apis/common"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationData) DeepCopyInto(out *ApplicationData) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationData.
func (in *ApplicationData) DeepCopy() *ApplicationData {
	if in == nil {
		return nil
	}
	out := new(ApplicationData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationData) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationDataList) DeepCopyInto(out *ApplicationDataList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationDataList.
func (in *ApplicationDataList) DeepCopy() *ApplicationDataList {
	if in == nil {
		return nil
	}
	out := new(ApplicationDataList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApplicationDataList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationDataSpec) DeepCopyInto(out *ApplicationDataSpec) {
	*out = *in
	if in.SourceFiles != nil {
		in, out := &in.SourceFiles, &out.SourceFiles
		*out = make([]SourceFile, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationDataSpec.
func (in *ApplicationDataSpec) DeepCopy() *ApplicationDataSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationDataSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationDataStatus) DeepCopyInto(out *ApplicationDataStatus) {
	*out = *in
	if in.PreprocessedFiles != nil {
		in, out := &in.PreprocessedFiles, &out.PreprocessedFiles
		*out = make([]PreprocessedFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]common.Condition, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationDataStatus.
func (in *ApplicationDataStatus) DeepCopy() *ApplicationDataStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationDataStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileInfo) DeepCopyInto(out *FileInfo) {
	*out = *in
	in.LastModified.DeepCopyInto(&out.LastModified)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileInfo.
func (in *FileInfo) DeepCopy() *FileInfo {
	if in == nil {
		return nil
	}
	out := new(FileInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImportingFile) DeepCopyInto(out *ImportingFile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImportingFile.
func (in *ImportingFile) DeepCopy() *ImportingFile {
	if in == nil {
		return nil
	}
	out := new(ImportingFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnownledgeBase) DeepCopyInto(out *KnownledgeBase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnownledgeBase.
func (in *KnownledgeBase) DeepCopy() *KnownledgeBase {
	if in == nil {
		return nil
	}
	out := new(KnownledgeBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnownledgeBase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnownledgeBaseList) DeepCopyInto(out *KnownledgeBaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KnownledgeBase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnownledgeBaseList.
func (in *KnownledgeBaseList) DeepCopy() *KnownledgeBaseList {
	if in == nil {
		return nil
	}
	out := new(KnownledgeBaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KnownledgeBaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnownledgeBaseSpec) DeepCopyInto(out *KnownledgeBaseSpec) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]ImportingFile, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnownledgeBaseSpec.
func (in *KnownledgeBaseSpec) DeepCopy() *KnownledgeBaseSpec {
	if in == nil {
		return nil
	}
	out := new(KnownledgeBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnownledgeBaseStatus) DeepCopyInto(out *KnownledgeBaseStatus) {
	*out = *in
	if in.ParsedFiles != nil {
		in, out := &in.ParsedFiles, &out.ParsedFiles
		*out = make([]ParsedFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnownledgeBaseStatus.
func (in *KnownledgeBaseStatus) DeepCopy() *KnownledgeBaseStatus {
	if in == nil {
		return nil
	}
	out := new(KnownledgeBaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParsedFile) DeepCopyInto(out *ParsedFile) {
	*out = *in
	in.File.DeepCopyInto(&out.File)
	in.ImportedTime.DeepCopyInto(&out.ImportedTime)
	out.Condition = in.Condition
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParsedFile.
func (in *ParsedFile) DeepCopy() *ParsedFile {
	if in == nil {
		return nil
	}
	out := new(ParsedFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreprocessedFile) DeepCopyInto(out *PreprocessedFile) {
	*out = *in
	in.SourceFile.DeepCopyInto(&out.SourceFile)
	in.ProcessedFile.DeepCopyInto(&out.ProcessedFile)
	out.Condition = in.Condition
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreprocessedFile.
func (in *PreprocessedFile) DeepCopy() *PreprocessedFile {
	if in == nil {
		return nil
	}
	out := new(PreprocessedFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceFile) DeepCopyInto(out *SourceFile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceFile.
func (in *SourceFile) DeepCopy() *SourceFile {
	if in == nil {
		return nil
	}
	out := new(SourceFile)
	in.DeepCopyInto(out)
	return out
}
